services:
  db:
    image: postgres:15-alpine
    container_name: sooryas-postgres
    restart: always
    environment:
      POSTGRES_USER: soorya_admin
      POSTGRES_PASSWORD: soorya_password
      POSTGRES_DB: sooryas_parlour_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
